server.port=8081
server.serverlet.context-path=/app

value.name = "diego"
value.apellido = "perez"
value.random = ${random.value}

user.email = "diego@gmail.com"
user.password="123456"
user.age=25

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
debug=true

